ARG NODE_VERSION="20.19.5"
ARG DEBIAN_VERSION="trixie"

FROM docker.io/node:${NODE_VERSION}-${DEBIAN_VERSION}-slim AS admin-builder

WORKDIR /build

COPY --link ["admin/package.json", "admin/yarn.lock", "./"]    

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn,sharing=locked \
    yarn install --frozen-lockfile

COPY --link admin ./

RUN yarn build


FROM docker.io/node:${NODE_VERSION}-${DEBIAN_VERSION}-slim AS server-builder

WORKDIR /build

COPY --link ["server/package.json", "server/yarn.lock", "./"]

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn,sharing=locked \ 
    yarn install --frozen-lockfile

COPY --link server ./

COPY --from=admin-builder /build/dist ./front/admin


FROM docker.io/node:${NODE_VERSION}-${DEBIAN_VERSION}-slim AS runner

ARG UID="991"
ARG GID="991"

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    ; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache \
    && apt-get update \
    && apt-get install -yqq --no-install-recommends \ 
    tini

RUN groupadd -g "${GID}" wikimoe \
    && useradd -l -u "${UID}" -g "${GID}" -m -d /server wikimoe

USER wikimoe
WORKDIR /server

COPY --chown=wikimoe:wikimoe --from=server-builder /build  ./

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["yarn", "start"]
